---

x-common-settings:
  &common-settings
  build:
    context: .
    dockerfile: "./docker/${DOCKERFILE:-NostalgiaForInfinityX6}"
  restart: unless-stopped
  volumes:
    - "./user_data:/freqtrade/user_data"
    - "./user_data/data:/freqtrade/user_data/data"
    - "./configs:/freqtrade/configs"
    - "./config-private.json:/freqtrade/config-private.json"
    - "./config-${FREQTRADE__EXCHANGE__NAME:-binance}.json:/freqtrade/config.json"
    - "./${FREQTRADE__STRATEGY:-NostalgiaForInfinityX6}.py:/freqtrade/${FREQTRADE__STRATEGY:-NostalgiaForInfinityX6}.py"
    - "./NostalgiaForInfinityX6.py:/freqtrade/NostalgiaForInfinityX6.py"

  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:${FREQTRADE__API_SERVER__LISTEN_PORT:-8080}"]
    interval: 1m30s
    timeout: 10s
    retries: 3
    start_period: 40s
    start_interval: 5s
  env_file:
    - path: .env
      required: true # default true

services:
  freqtrade:
    <<: *common-settings
    container_name: ${FREQTRADE__BOT_NAME:-Example_Test_Account}_${FREQTRADE__EXCHANGE__NAME:-binance}_${FREQTRADE__TRADING_MODE:-futures}-${FREQTRADE__STRATEGY:-NostalgiaForInfinityX6}
    ports:
      - "127.0.0.1:${FREQTRADE__API_SERVER__LISTEN_PORT:-8080}:${FREQTRADE__API_SERVER__LISTEN_PORT:-8080}"
    # Default command used when running `docker compose up`
    command: >
      trade
      --db-url sqlite:////freqtrade/user_data/${FREQTRADE__BOT_NAME:-Example_Test_Account}_${FREQTRADE__EXCHANGE__NAME:-binance}_${FREQTRADE__TRADING_MODE:-futures}-tradesv3.sqlite
      --log-file user_data/logs/${FREQTRADE__BOT_NAME:-Example_Test_Account}-${FREQTRADE__EXCHANGE__NAME:-binance}-${FREQTRADE__STRATEGY:-NostalgiaForInfinityX6}-${FREQTRADE__TRADING_MODE:-futures}.log
      --strategy-path .
      --config config.json